# Generated by Django 3.0.3 on 2020-09-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('summary', models.TextField(max_length=1000, null=True)),
                ('jibun_address', models.CharField(max_length=45, null=True)),
                ('road_address', models.CharField(max_length=45, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, default=0.0, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=15, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.PositiveIntegerField(help_text='Enter price over 0')),
                ('summary', models.TextField(max_length=1000, null=True)),
                ('caution', models.TextField(max_length=1000, null=True)),
                ('refund_policy', models.TextField(max_length=1000, null=True)),
                ('cancel_policy', models.TextField(max_length=1000, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Company')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='RoomLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='RoomEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Equipments')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='equipements',
            field=models.ManyToManyField(through='space.RoomEquipments', to='space.Equipments'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_like',
            field=models.ManyToManyField(related_name='room_like_set', through='space.RoomLike', to='account.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_reviews',
            field=models.ManyToManyField(related_name='room_reviews_set', through='space.RoomReview', to='account.User'),
        ),
        migrations.CreateModel(
            name='CompanyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_like',
            field=models.ManyToManyField(related_name='company_like_set', through='space.CompanyLike', to='account.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_reviews',
            field=models.ManyToManyField(related_name='company_review_set', through='space.RoomReview', to='account.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='space.CompanyType'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Owner'),
        ),
    ]
